spring:
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: "server-keypair"
            password: "server-key-p455w0rd"
          keystore:
            location: "classpath:jks/server-keystore.jks"
            password: "server-keystore-p455w0rd"
            type: "JKS"
          truststore:
            location: "classpath:jks/client-truststore.jks"
            password: "client-truststore-p455w0rd"
            type: "JKS"

server:
  port: 8443
  ssl:
    bundle: "web-server"
    enabled: true

client:
  default-uri: https://localhost:8443/ws/
